name: deploy

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: 3.x
          cache: pip

      - name: Install required packages from apt
        run: |
          sudo apt-get update
          sudo apt-get install zlib1g-dev libjpeg-dev python3-pythonmagick \
          inkscape xvfb poppler-utils libfile-mimeinfo-perl qpdf \
          libimage-exiftool-perl ffmpeg libmagickwand-dev libreoffice

      - name: Install python packages with pip
        run: pip install -r requirements.txt

      - name: Cache
        uses: actions/cache@v4
        with:
          # A list of files, directories, and wildcard patterns to cache and restore
          path: |
            previews
          # An explicit key for restoring and saving the cache
          key: ${{ runner.os }}-${{ hashFiles('**/previews') }}

      - name: Generate index
        run: staticdirindex . --sitename="IJRU Archive" --baseurl="https://archive.ijru.sport"

      - name: GitHub Pages action
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .
          user_name: Github Actions
          user_email: archive@ijru.sport
          cname: archive.ijru.sport
          exclude_assets: ".github,.listignore,.gitignore,README.md,requirements.txt,**/*.lock"
